-- ============================================================
-- COUNTRIES TABLE + SEED ALL 195 COUNTRIES
-- Run: npx supabase db query --linked -f supabase/countries_seed.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS public.countries (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  code CHAR(2) NOT NULL UNIQUE,
  phone_code TEXT,
  region TEXT
);

-- Enable RLS
ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;

-- Everyone can read countries
CREATE POLICY "Anyone can read countries" ON public.countries FOR SELECT USING (true);

-- Seed all 195 UN-recognized countries
INSERT INTO public.countries (name, code, phone_code, region) VALUES
  ('Afghanistan', 'AF', '+93', 'Asia'),
  ('Albania', 'AL', '+355', 'Europe'),
  ('Algeria', 'DZ', '+213', 'Africa'),
  ('Andorra', 'AD', '+376', 'Europe'),
  ('Angola', 'AO', '+244', 'Africa'),
  ('Antigua and Barbuda', 'AG', '+1-268', 'Americas'),
  ('Argentina', 'AR', '+54', 'Americas'),
  ('Armenia', 'AM', '+374', 'Asia'),
  ('Australia', 'AU', '+61', 'Oceania'),
  ('Austria', 'AT', '+43', 'Europe'),
  ('Azerbaijan', 'AZ', '+994', 'Asia'),
  ('Bahamas', 'BS', '+1-242', 'Americas'),
  ('Bahrain', 'BH', '+973', 'Asia'),
  ('Bangladesh', 'BD', '+880', 'Asia'),
  ('Barbados', 'BB', '+1-246', 'Americas'),
  ('Belarus', 'BY', '+375', 'Europe'),
  ('Belgium', 'BE', '+32', 'Europe'),
  ('Belize', 'BZ', '+501', 'Americas'),
  ('Benin', 'BJ', '+229', 'Africa'),
  ('Bhutan', 'BT', '+975', 'Asia'),
  ('Bolivia', 'BO', '+591', 'Americas'),
  ('Bosnia and Herzegovina', 'BA', '+387', 'Europe'),
  ('Botswana', 'BW', '+267', 'Africa'),
  ('Brazil', 'BR', '+55', 'Americas'),
  ('Brunei', 'BN', '+673', 'Asia'),
  ('Bulgaria', 'BG', '+359', 'Europe'),
  ('Burkina Faso', 'BF', '+226', 'Africa'),
  ('Burundi', 'BI', '+257', 'Africa'),
  ('Cabo Verde', 'CV', '+238', 'Africa'),
  ('Cambodia', 'KH', '+855', 'Asia'),
  ('Cameroon', 'CM', '+237', 'Africa'),
  ('Canada', 'CA', '+1', 'Americas'),
  ('Central African Republic', 'CF', '+236', 'Africa'),
  ('Chad', 'TD', '+235', 'Africa'),
  ('Chile', 'CL', '+56', 'Americas'),
  ('China', 'CN', '+86', 'Asia'),
  ('Colombia', 'CO', '+57', 'Americas'),
  ('Comoros', 'KM', '+269', 'Africa'),
  ('Congo (DRC)', 'CD', '+243', 'Africa'),
  ('Congo (Republic)', 'CG', '+242', 'Africa'),
  ('Costa Rica', 'CR', '+506', 'Americas'),
  ('Croatia', 'HR', '+385', 'Europe'),
  ('Cuba', 'CU', '+53', 'Americas'),
  ('Cyprus', 'CY', '+357', 'Europe'),
  ('Czech Republic', 'CZ', '+420', 'Europe'),
  ('Denmark', 'DK', '+45', 'Europe'),
  ('Djibouti', 'DJ', '+253', 'Africa'),
  ('Dominica', 'DM', '+1-767', 'Americas'),
  ('Dominican Republic', 'DO', '+1-809', 'Americas'),
  ('Ecuador', 'EC', '+593', 'Americas'),
  ('Egypt', 'EG', '+20', 'Africa'),
  ('El Salvador', 'SV', '+503', 'Americas'),
  ('Equatorial Guinea', 'GQ', '+240', 'Africa'),
  ('Eritrea', 'ER', '+291', 'Africa'),
  ('Estonia', 'EE', '+372', 'Europe'),
  ('Eswatini', 'SZ', '+268', 'Africa'),
  ('Ethiopia', 'ET', '+251', 'Africa'),
  ('Fiji', 'FJ', '+679', 'Oceania'),
  ('Finland', 'FI', '+358', 'Europe'),
  ('France', 'FR', '+33', 'Europe'),
  ('Gabon', 'GA', '+241', 'Africa'),
  ('Gambia', 'GM', '+220', 'Africa'),
  ('Georgia', 'GE', '+995', 'Asia'),
  ('Germany', 'DE', '+49', 'Europe'),
  ('Ghana', 'GH', '+233', 'Africa'),
  ('Greece', 'GR', '+30', 'Europe'),
  ('Grenada', 'GD', '+1-473', 'Americas'),
  ('Guatemala', 'GT', '+502', 'Americas'),
  ('Guinea', 'GN', '+224', 'Africa'),
  ('Guinea-Bissau', 'GW', '+245', 'Africa'),
  ('Guyana', 'GY', '+592', 'Americas'),
  ('Haiti', 'HT', '+509', 'Americas'),
  ('Honduras', 'HN', '+504', 'Americas'),
  ('Hungary', 'HU', '+36', 'Europe'),
  ('Iceland', 'IS', '+354', 'Europe'),
  ('India', 'IN', '+91', 'Asia'),
  ('Indonesia', 'ID', '+62', 'Asia'),
  ('Iran', 'IR', '+98', 'Asia'),
  ('Iraq', 'IQ', '+964', 'Asia'),
  ('Ireland', 'IE', '+353', 'Europe'),
  ('Israel', 'IL', '+972', 'Asia'),
  ('Italy', 'IT', '+39', 'Europe'),
  ('Ivory Coast', 'CI', '+225', 'Africa'),
  ('Jamaica', 'JM', '+1-876', 'Americas'),
  ('Japan', 'JP', '+81', 'Asia'),
  ('Jordan', 'JO', '+962', 'Asia'),
  ('Kazakhstan', 'KZ', '+7', 'Asia'),
  ('Kenya', 'KE', '+254', 'Africa'),
  ('Kiribati', 'KI', '+686', 'Oceania'),
  ('Kosovo', 'XK', '+383', 'Europe'),
  ('Kuwait', 'KW', '+965', 'Asia'),
  ('Kyrgyzstan', 'KG', '+996', 'Asia'),
  ('Laos', 'LA', '+856', 'Asia'),
  ('Latvia', 'LV', '+371', 'Europe'),
  ('Lebanon', 'LB', '+961', 'Asia'),
  ('Lesotho', 'LS', '+266', 'Africa'),
  ('Liberia', 'LR', '+231', 'Africa'),
  ('Libya', 'LY', '+218', 'Africa'),
  ('Liechtenstein', 'LI', '+423', 'Europe'),
  ('Lithuania', 'LT', '+370', 'Europe'),
  ('Luxembourg', 'LU', '+352', 'Europe'),
  ('Madagascar', 'MG', '+261', 'Africa'),
  ('Malawi', 'MW', '+265', 'Africa'),
  ('Malaysia', 'MY', '+60', 'Asia'),
  ('Maldives', 'MV', '+960', 'Asia'),
  ('Mali', 'ML', '+223', 'Africa'),
  ('Malta', 'MT', '+356', 'Europe'),
  ('Marshall Islands', 'MH', '+692', 'Oceania'),
  ('Mauritania', 'MR', '+222', 'Africa'),
  ('Mauritius', 'MU', '+230', 'Africa'),
  ('Mexico', 'MX', '+52', 'Americas'),
  ('Micronesia', 'FM', '+691', 'Oceania'),
  ('Moldova', 'MD', '+373', 'Europe'),
  ('Monaco', 'MC', '+377', 'Europe'),
  ('Mongolia', 'MN', '+976', 'Asia'),
  ('Montenegro', 'ME', '+382', 'Europe'),
  ('Morocco', 'MA', '+212', 'Africa'),
  ('Mozambique', 'MZ', '+258', 'Africa'),
  ('Myanmar', 'MM', '+95', 'Asia'),
  ('Namibia', 'NA', '+264', 'Africa'),
  ('Nauru', 'NR', '+674', 'Oceania'),
  ('Nepal', 'NP', '+977', 'Asia'),
  ('Netherlands', 'NL', '+31', 'Europe'),
  ('New Zealand', 'NZ', '+64', 'Oceania'),
  ('Nicaragua', 'NI', '+505', 'Americas'),
  ('Niger', 'NE', '+227', 'Africa'),
  ('Nigeria', 'NG', '+234', 'Africa'),
  ('North Korea', 'KP', '+850', 'Asia'),
  ('North Macedonia', 'MK', '+389', 'Europe'),
  ('Norway', 'NO', '+47', 'Europe'),
  ('Oman', 'OM', '+968', 'Asia'),
  ('Pakistan', 'PK', '+92', 'Asia'),
  ('Palau', 'PW', '+680', 'Oceania'),
  ('Palestine', 'PS', '+970', 'Asia'),
  ('Panama', 'PA', '+507', 'Americas'),
  ('Papua New Guinea', 'PG', '+675', 'Oceania'),
  ('Paraguay', 'PY', '+595', 'Americas'),
  ('Peru', 'PE', '+51', 'Americas'),
  ('Philippines', 'PH', '+63', 'Asia'),
  ('Poland', 'PL', '+48', 'Europe'),
  ('Portugal', 'PT', '+351', 'Europe'),
  ('Qatar', 'QA', '+974', 'Asia'),
  ('Romania', 'RO', '+40', 'Europe'),
  ('Russia', 'RU', '+7', 'Europe'),
  ('Rwanda', 'RW', '+250', 'Africa'),
  ('Saint Kitts and Nevis', 'KN', '+1-869', 'Americas'),
  ('Saint Lucia', 'LC', '+1-758', 'Americas'),
  ('Saint Vincent and the Grenadines', 'VC', '+1-784', 'Americas'),
  ('Samoa', 'WS', '+685', 'Oceania'),
  ('San Marino', 'SM', '+378', 'Europe'),
  ('Sao Tome and Principe', 'ST', '+239', 'Africa'),
  ('Saudi Arabia', 'SA', '+966', 'Asia'),
  ('Senegal', 'SN', '+221', 'Africa'),
  ('Serbia', 'RS', '+381', 'Europe'),
  ('Seychelles', 'SC', '+248', 'Africa'),
  ('Sierra Leone', 'SL', '+232', 'Africa'),
  ('Singapore', 'SG', '+65', 'Asia'),
  ('Slovakia', 'SK', '+421', 'Europe'),
  ('Slovenia', 'SI', '+386', 'Europe'),
  ('Solomon Islands', 'SB', '+677', 'Oceania'),
  ('Somalia', 'SO', '+252', 'Africa'),
  ('South Africa', 'ZA', '+27', 'Africa'),
  ('South Korea', 'KR', '+82', 'Asia'),
  ('South Sudan', 'SS', '+211', 'Africa'),
  ('Spain', 'ES', '+34', 'Europe'),
  ('Sri Lanka', 'LK', '+94', 'Asia'),
  ('Sudan', 'SD', '+249', 'Africa'),
  ('Suriname', 'SR', '+597', 'Americas'),
  ('Sweden', 'SE', '+46', 'Europe'),
  ('Switzerland', 'CH', '+41', 'Europe'),
  ('Syria', 'SY', '+963', 'Asia'),
  ('Taiwan', 'TW', '+886', 'Asia'),
  ('Tajikistan', 'TJ', '+992', 'Asia'),
  ('Tanzania', 'TZ', '+255', 'Africa'),
  ('Thailand', 'TH', '+66', 'Asia'),
  ('Timor-Leste', 'TL', '+670', 'Asia'),
  ('Togo', 'TG', '+228', 'Africa'),
  ('Tonga', 'TO', '+676', 'Oceania'),
  ('Trinidad and Tobago', 'TT', '+1-868', 'Americas'),
  ('Tunisia', 'TN', '+216', 'Africa'),
  ('Turkey', 'TR', '+90', 'Europe'),
  ('Turkmenistan', 'TM', '+993', 'Asia'),
  ('Tuvalu', 'TV', '+688', 'Oceania'),
  ('Uganda', 'UG', '+256', 'Africa'),
  ('Ukraine', 'UA', '+380', 'Europe'),
  ('United Arab Emirates', 'AE', '+971', 'Asia'),
  ('United Kingdom', 'GB', '+44', 'Europe'),
  ('United States', 'US', '+1', 'Americas'),
  ('Uruguay', 'UY', '+598', 'Americas'),
  ('Uzbekistan', 'UZ', '+998', 'Asia'),
  ('Vanuatu', 'VU', '+678', 'Oceania'),
  ('Vatican City', 'VA', '+379', 'Europe'),
  ('Venezuela', 'VE', '+58', 'Americas'),
  ('Vietnam', 'VN', '+84', 'Asia'),
  ('Yemen', 'YE', '+967', 'Asia'),
  ('Zambia', 'ZM', '+260', 'Africa'),
  ('Zimbabwe', 'ZW', '+263', 'Africa')
ON CONFLICT (code) DO NOTHING;
